[info]
name = Standard
[Func0]
fields = __all,
func_name = replace
module = puddlestuff.functions
arguments = Dj, DJ, False, True
[Func1]
fields = __all,
func_name = replace
module = puddlestuff.functions
arguments = Mc, MC, False, True
[Func2]
fields = __all,
func_name = replace
module = puddlestuff.functions
arguments = feat, Feat, False, True
[Func3]
fields = __all,
func_name = replace
module = puddlestuff.functions
arguments = Vs, vs, False, True
[Func4]
fields = comment,
func_name = remove_fields
module = puddlestuff.functions
arguments = ,
