[info]
name = Path_lowername
[Func0]
fields = __filename,
func_name = replace
module = puddlestuff.functions
arguments = " ", _, False, False
[Func1]
fields = __filename,
func_name = replace
module = puddlestuff.functions
arguments = %20, _, False, False
[Func2]
fields = __filename,
func_name = replace
module = puddlestuff.functions
arguments = " å", a, False, False
[Func3]
fields = __filename,
func_name = replace
module = puddlestuff.functions
arguments = ä, ae, False, False
[Func4]
fields = __filename,
func_name = replace
module = puddlestuff.functions
arguments = Ö, o, False, False
[Func5]
fields = __filename,
func_name = titleCase
module = puddlestuff.functions
arguments = lower case, ""
[Func6]
fields = __dirpath,
func_name = titleCase
module = puddlestuff.functions
arguments = lower case, ""
[Func7]
fields = __dirpath,
func_name = replace
module = puddlestuff.functions
arguments = " ", _, False, False
